# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

interval: 500ms

tasks:
  build:
    cmd: go build

  build:watch:
    cmd: go build
    watch: true
    sources:
      - '**/*.go'
    generates:
      - node-alias{{exeExt}}
    method: timestamp

  build:linux:
    env:
      GOOS: linux
      GOARCH: amd64
    cmd: go build

  build:darwin:
    env:
      GOOS: darwin
      GOARCH: arm64
    cmd: go build

  build:all:
    cmd: goreleaser release --clean --snapshot

  gen:completions:
    desc: Regenerate completion files
    cmds:
      - go build
      - ./node-alias{{exeExt}} completion bash > ./completions/node-alias.bash
      - ./node-alias{{exeExt}} completion zsh > ./completions/node-alias.zsh
      - ./node-alias{{exeExt}} completion fish > ./completions/node-alias.fish
      - ./node-alias{{exeExt}} completion powershell > ./completions/node-alias.ps1
